version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "01:00"
      timezone: "America/Los_Angeles"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "deps"
      include: "scope"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "01:00"
      timezone: "America/Los_Angeles"
    labels:
      - "dependencies"
      - "npm"
      - "worker"
    commit-message:
      prefix: "deps"
      include: "scope"
    versioning-strategy: increase
    groups:
      dev-dependencies:
        patterns:
          - "eslint*"
          - "typescript"
          - "@types/*"
          - "wrangler"
          - "@cloudflare/*"
          - "vite*"
          - "@vitest/*"
          - "@biomejs/*"
        update-types:
          - "major"
          - "minor"
          - "patch"
    open-pull-requests-limit: 10
